= Context
:chapter: Context
include::_notify-bug-admonition.adoc[]


== Context diagram
// This is an example diagram to show how to include a structurizr-generated diagram
[plantuml, {plantumldir}SystemContext, svg, opts="interactive"]     
----
include::{structurizrdir}/SystemContext.plantuml[]
----

== What is this softare system about ?
Getting "true" public transport delay is often impossible.
Because the organism responsible for displaying delays is also the organism that allow transports to run.
As a consequence, it is not always their best move to display effective transport delay.
This system exists to overcome that. 

== What is it that's being built?
We will build a system that allow us to easily compare official time table with effective transport delay by

. Asking users in transports to tell us if transport is late or not
. Comparing effective transport location with the one provided by real-time location, when it exists

== How does it fit into the existing environment? (e.g. systems, business
processes, etc)

As we're doing this as a startup, we have no internal context.
However, there is an external context.

We will use services of https://www.navitia.io/[navitia], which provides time tables for all France cities public transport systems, but also intercity train.

We will also use geolocation services provided by SNCF (for intercity trains) and other providers wher possible.

== Who is using it? (users, roles, actors, personas, etc)
We currently envision two types of useers (who can in fact be the same person at different times)

. The waiting user, to which we will send accurate crossing schedule information.
. The user already in transport, which can inform waiting user if the train was on time or not

// This include allows enhancers to have their content include "automagically". Don't remove it!
include::{enhancements-dir}/_01-context.adoc[leveloffset=+1]