= Functional Overview
:chapter: Functional%20Overview
include::_notify-bug-admonition.adoc[]

This system allows a person waiting for a public transport to have informations on transport schedule, as provided by people upstream in the same public transport. 
Imagine that as a crowdsourced SMS from a friend.

Features are quite simple.

== For a waiting person
When someone waits for a transport, kafkatrain detects (from user location and timetables) which are the possible transports the person wants to go in.
If multiple transports matches, the application allows user to select which transport he is waiting for.
Once a transport has been selected, information from upstream users is presented.
This information will typically take the form of

[quote]
At stop "name of stop", transport was "on time|late by n minutes"

NOTE: As of today, we don't envision the UI of application

== For someone in a transport

Once the user is in the public transport, and the transport is moving, application simply sends a message notifying the system that transport is on way.

// This include allows enhancers to have their content include "automagically". Don't remove it!
include::{enhancements-dir}/_02-functional_overview.adoc[leveloffset=+1]