= Quality Attributes
:chapter: Quality%20Attributes
include::_notify-bug-admonition.adoc[]

== Common constraints

Performance (e.g. latency and throughput)::
All users should have application available in 5 seconds.

Scalability (e.g. data and traffic volumes)::
We expect a first deployment with 1.000 users (and 100 simultaneous connections of users)

Availability (e.g. uptime, downtime, scheduled maintenance, 24x7,99.9%, etc)::
Application will initially be available on a https://uptime.is/99.9[99.9% basis]

Security (e.g. authentication, authorisation, data confidentiality, etc)::
No user data should be stored by system.
Authentication and authorization will be managed using OpenID Connect with the usual id providers (Google, Facebook, ...)

Extensibility::
Application will be extended to various geographic areas and types of public transport systems (buses, trains, boats), but there will be no feature extensibility

Flexibility::
Application is not supposed to be flexible

Auditing::
We must be able to audit the timetables provided by Navitia as well as the real-time positions.
We must also be able to audit what informations users in transit send 
to blacklist the ones that will (because shit happens) try to abuse the system.

Monitoring and management::
Usual system monitoring will be used.

Reliability::
Besides, we will monitor the number of users in transit and waiting and the delay between the time when one user starts his transit and another, on the same line, receive the delay information.

Failover/disaster recovery targets (e.g. manual vs automatic, how long will this take?)::
We should be able to recover data center loss in less than one day.

Business continuity::
N/A
Interoperability::
N/A

Legal, compliance and regulatory requirements (e.g. data protection act)::
N/A

Internationalisation (i18n) and localisation (L10n)::
Application will be deployed in all countries where public transport systems provide APIs (and have potential delays).
For the sake of easiness, application will be first deployed in France.

Accessibility::
Don't know how to validate that.

Usability::
Don't know how to validate that.


== Specifc constraints

These constraints maps to the relationships expressed in <<Context>>

=== Ingesting time tables
Ingesting time tables from Navitia should be done each day.
The process should be monitored since there should be no day where this data is not ingested.
THis ingestion should be done prior the first release (application has no interest without that).

=== Ingestion real-time positions
This should be done in a continuous stream.
Ingestion should not have delay greater than one minute.
Application should be able to work without this information.

=== Seeing train delays
Delays should be communicated to user in less than 1 s.
If user connection to system dont allow that, delays will be sent to user with a notification indicating that network is not performant enough to have accurate timetables.

=== Informing application that transport is running
A transport is considered as moving after 5 seconds of continuous move.
After this delay, signal should be sent in less than 1 s.


// This include allows enhancers to have their content include "automagically". Don't remove it!
include::{enhancements-dir}/_03-quality_attributes.adoc[leveloffset=+1]