= Constraints
:chapter: Constraints
include::_notify-bug-admonition.adoc[]

== Common constraints
Time, budget and resources::
Project will be built by Nicolas Delsaux and Logan Hauspie.
Budget is zero, as it is an example.
Application is expected to be delivered ... one day

Approved technology lists and technology constraints::
Server-side components of application will be depolyed as containers.

Target deployment platform::
Application will be deployed on Google Kubernetes Cluster.

Existing systems and integration standards::
TODO

Local standards (e.g. development, coding, etc)::
TODO

Public standards (e.g. HTTP, SOAP, XML, XML Schema, WSDL, etc)::
TODO

Standard protocols::
TODO

Standard message formats::
TODO

Size of the software development team::
Two persons at best

Skill profile of the software development team::
Developers are skilled on server-side, less on front-end.

Nature of the software being built (e.g. tactical or strategic)::
Strategic, as it is the only product of our startup.

Political constraints::
TODO

Use of internal intellectual property::
TODO

// This include allows enhancers to have their content include "automagically". Don't remove it!
include::{enhancements-dir}/_04-constraints.adoc[leveloffset=+1]