Style/Encoding:
  Enabled: false

Layout/EndOfLine:
  EnforcedStyle: lf

Metrics/LineLength:
  Max: 180

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/AbcSize:
  Max: 30

Metrics/ParameterLists:
  Max: 7
