@startuml

boundary SequenceDiagramGenerator
SequenceDiagramGenerator -> startVisit
activate startVisit

startVisit -> startVisit: getSoftwareSystems
note left
  get containers
end note

startVisit -> startVisit: getSoftwareSystems
note left
  get components
end note

startVisit -> createProjectRootFor: get relative containers and components
activate createProjectRootFor

createProjectRootFor -> createProjectRootFor: getAssociatedContainersOf
note left
  get relative containers
end note

createProjectRootFor -> createProjectRootFor: getComponentsToScanFor
note left
  get relative components
end note

createProjectRootFor -> startVisit
deactivate createProjectRootFor

startVisit -> startVisit: parseAllSources
note left
  get sources path
end note

startVisit -> analyzeCalls: get graph model
activate analyzeCalls


boundary JavaParserVisitorForBuildingCallGraph
analyzeCalls -> JavaParserVisitorForBuildingCallGraph: parse Java
activate JavaParserVisitorForBuildingCallGraph

JavaParserVisitorForBuildingCallGraph -> analyzeCalls: parsed Java
deactivate JavaParserVisitorForBuildingCallGraph

analyzeCalls -> startVisit: Graph model
deactivate analyzeCalls

startVisit -> SequenceDiagramGenerator
deactivate startVisit

SequenceDiagramGenerator -> endVisit
activate endVisit

endVisit -> generatePlantUMLDiagramFor: generate UML files

endVisit -> SequenceDiagramGenerator
deactivate endVisit

@enduml