@startuml(id=SystemContext)
scale max 2000x2000
title Software System - System Context
caption An example of a System Context diagram.

skinparam {
  shadowing false
  arrowColor #707070
  actorBorderColor #707070
  componentBorderColor #707070
  rectangleBorderColor #707070
  noteBackgroundColor #ffffff
  noteBorderColor #707070
  rectangleFontColor #ffffff
  rectangleStereotypeFontColor #ffffff
}
rectangle 2 <<Software System>> #dddddd [
  Software System
  --
  My software system.
]
rectangle 1 <<Person>> #dddddd [
  User
  --
  A user of my software system.
]
1 .[#707070].> 2 : Uses
@enduml
