# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: On master push perform build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B install --file pom.xml -Daadarchi.github.token=$TOKEN_FOR_GITHUB
        env:
          TOKEN_FOR_GITHUB: ${{ secrets.TOKEN_FOR_GITHUB }}
