# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: On GitHub Release perform equivalent maven release

#on:
#  release:
#    types:
#      - created
#      - published

on:
  workflow_dispatch:
    inputs:
      releaseversion:
        description: 'Release version'
        required: true
        default: '2.4.0'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - run: echo "Will perform a maven release with public version ${{ github.event.inputs.releaseversion }}"

      - uses: actions/checkout@v2
      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
          cache: 'maven'
      - name: Do not forget to configure Maven Settings!
        uses: s4u/maven-settings-action@v2.6.0
        with:
          servers: |
            [{
                "id": "ossrh",
                "username": "${{ secrets.OSS_SONATYPE_USERNAME }}",
                "password": "${{ secrets.OSS_SONATYPE_PASSWORD }}"
            }]
#          properties: '[{ "gpg-private-key": "${{ secrets.MAVEN_GPG_PRIVATE_KEY }}" }, { "gpg-passphrase": "${{secrets.MAVEN_GPG_PASSPHRASE}}" }]'
      - name: Build with Maven
        run: mvn -B release:prepare release:perform -Prelease -DreleaseVersion=${{ github.event.inputs.releaseversion }} --file pom.xml -Daadarchi.github.token=$TOKEN_FOR_GITHUB
        env:
          TOKEN_FOR_GITHUB: ${{ secrets.TOKEN_FOR_GITHUB }}
          MAVEN_USERNAME: ${{ secrets.OSS_SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSS_SONATYPE_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
