name: On tag created generate GitHub release with notes
on:
  on: [release]
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: lakto/gren-action@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          options: '--override'