name: On tag update readme to have the correct version
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'     
        required: true
        default: '0.1.4'
#  push:
#    tags:
#      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  replace_version_in_README:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Modify version number in README
        uses: mingjun97/file-regex-replace@master
        with:
          regex: '=[0-9]+\.[0-9]+\.[0-9]+ '
          replacement: '=${{ github.event.inputs.tag }} '
          include: '^README\.md'    # Optional, defaults to ".*"
      - name: Commit the updated README
        uses: devops-infra/action-commit-push@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          add_timestamp: true
          commit_prefix: "🤖"
          commit_message: "Updated readme"
          force: false
          target_branch: master