name: On tag update readme to have the correct version
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  replace_version_in_README:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Modify version number in README
        uses: mingjun97/file-regex-replace@master
        with:
          regex: '=[0-9]+\.[0-9]+\.[0-9]+ '
          replacement: '=${{ github.ref }} '
          include: '^README\.md'    # Optional, defaults to ".*"
      - name: Commit the updated README_name
        uses: devops-infra/action-commit-push@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          add_timestamp: true
          commit_prefix: "🤖"
          commit_message: "Updated readme to have version ${{ github.ref_name }} in"
          force: false
          target_branch: master