name: On tag created generate GitHub release notes
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate release notes
        uses: raulanatol/github-actions-releaser@main
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_FOR_GITHUB }}