name: On tag created generate GitHub release notes
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
    inputs:
      releaseversion:
        description: 'Release version'
        required: true
        default: "0.1.11"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate release notes
        uses: raulanatol/github-actions-releaser@main
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_FOR_GITHUB }}